### ISSUE TITLE
Error downloading files.

### ISSUE THREAD

**Issue by apiszcz** [p-ranav/merged_depth#1]
```
merged_depth >python utils\download_models.py
Traceback (most recent call last):
  File "utils\download_models.py", line 65, in <module>
    main()
  File "utils\download_models.py", line 62, in main
    extract_models(pretrained_models)
  File "utils\download_models.py", line 56, in extract_models
    with zipfile.ZipFile(file, 'r') as zip_ref:
  File "c:\g\vr\lw\python\lib\zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "c:\g\vr\lw\python\lib\zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by p-ranav** [comment]
That's odd, seems to work fine for me. Is there a `pretrained.zip` in that location? The download script first downloads a `pretrained.zip` file and then extracts the contents to a `pretrained` folder. 

If you're still having difficulty, you can download it from [here](https://drive.google.com/drive/folders/1seXeHWLaPU1iY14cC9yI6NPqeThL_aUu).

**Comment by apiszcz** [comment]
it requires access, sent the request, thank you.

**Comment by p-ranav** [comment]
Should be publicly accessible now. Sorry about that. 

You can check again if the script works OK.

**Comment by apiszcz** [comment]
Thank you, retrieved file.
