### ISSUE TITLE
Can't download models

### ISSUE THREAD

**Issue by eppppi** [p-ranav/merged_depth#10]
When I try `python3 -m merged_depth.utils.download_models`, following errors occurred

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/me/merged_depth/merged_depth/utils/download_models.py", line 65, in <module>
    main()
  File "/home/me/merged_depth/merged_depth/utils/download_models.py", line 62, in main
    extract_models(pretrained_models)
  File "/home/me/merged_depth/merged_depth/utils/download_models.py", line 56, in extract_models
    with zipfile.ZipFile(file, 'r') as zip_ref:
  File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

The content of pretrained/pretrained.zip is
```html
<HTML>
<HEAD>
<TITLE>Not Found</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Not Found</H1>
<H2>Error 404</H2>
</BODY>
</HTML>
```

How can I get the model?
Thanks!

**Comment by canadacow** [comment]
Same. Was excited to try it out as it's the first depth model I've found on github that isn't completely abandoned/out of date.

**Comment by p-ranav** [comment]
Sorry y'all, I accidentally deleted the pretrained ZIP when cleaning up my Google Drive. 

Can you check again? I've restored the file.

**Comment by canadacow** [comment]
Thanks for updating the pretrained.zip. The python script doesn't work with the URL but downloading it manually (constructing the URL manually) works just fine.

```
Using cache found in C:\Users\Dean/.cache\torch\hub\rwightman_gen-efficientnet-pytorch_master
Loading base model ()...Done.
Removing last two layers (global_pool & classifier).
Building Encoder-Decoder model..Done.
Using cache found in C:\Users\Dean/.cache\torch\hub\rwightman_gen-efficientnet-pytorch_master
Loading base model ()...Done.
Removing last two layers (global_pool & classifier).
Building Encoder-Decoder model..Done.
Loading weights:  ./pretrained/MiDaS_f6b98070.pt
Downloading: "https://github.com/facebookresearch/WSL-Images/archive/master.zip" to
``` 

Unfortunately https://github.com/facebookresearch/WSL-Images/archive/master.zip is now a 404 file.

**Comment by eppppi** [comment]
Thank you for uploading the file!
Unfortunately I'm also experiencing the same problem as canadacow.

**Comment by mmurray** [comment]
I also see a 404 for the WSL-images zip. Were either of you able to resolve the issue?

**Comment by p-ranav** [comment]
It seems the models are now available in [torch.hub](https://pytorch.org/docs/stable/hub.html).

One would have to acquire them like so:

```python
model = torch.hub.load('facebookresearch/WSL-Images', 'resnext101_32x16d_wsl')
```

**Comment by mmurray** [comment]
Thanks for the quick reply.  It looks like the code is already trying to load the models from torch.hub but the repository has moved. I submit a PR #11 with the updated repository, which fixes the 404 issue for me.
