### ISSUE TITLE
clarification about output

### ISSUE THREAD

**Issue by nithinvenny07** [p-ranav/merged_depth#3]
Hii @p-ranav 
thank so much for sharing your amazing work 
i wanted to know what output image represents, is it representing absolute depth or anything proportional to absolute depth?
what are the values in `average_depth` in infer.py represent?
if i want to get the absolute depth how can i get that

Thank you

**Comment by p-ranav** [comment]
It is intended to be absolute depth in meters (the accuracy of this is TBD). Some of the depth predictions (e.g., MiDaS) are not absolute but instead relative depth (https://github.com/intel-isl/MiDaS/issues/37). I'm using some linear parameters to scale these to absolute depth - using absolute depth predictions, e.g., AdaBins, as the basis for this scaling.
