### ISSUE TITLE
SGDepth Predictions Inverted

### ISSUE THREAD

**Issue by richardmarcus** [p-ranav/merged_depth#5]
It seems to me that the predicted values from SGDepth are inverted compared to other predictions.

(Also thank you for having this repository public! Really nice for comparing different depth networks!)

**Comment by p-ranav** [comment]
Thanks for reporting. Feel free to create a PR for any updates/improvements. I'd love for this to (1) improve on the results on an individual model, and (2) provide a way to better compare between models.
